import { Destination, Tip } from './types'

export const destinations: Destination[] = [
  {
    id: '1',
    slug: 'giappone',
    name: 'Giappone',
    country_code: 'JP',
    flag_emoji: '🇯🇵',
    region: 'asia',
    cities: ['Tokyo', 'Kyoto', 'Osaka', 'Hiroshima'],
    tags: ['Cultura', 'Cibo', 'Tecnologia'],
    member_count: 698,
    is_trending: true,
    is_emerging: false,
    groups: [
      { id: 'g1', name: 'Giappone 2025 — generale', whatsapp_url: 'https://chat.whatsapp.com/esempio1', member_count: 487, max_members: 1024, is_active: true },
      { id: 'g2', name: 'Tokyo city — ottobre/novembre', whatsapp_url: 'https://chat.whatsapp.com/esempio2', member_count: 211, max_members: 1024, is_active: true },
      { id: 'g3', name: 'Giappone primavera 2025', whatsapp_url: '', member_count: 1024, max_members: 1024, is_active: false },
    ],
  },
  {
    id: '2',
    slug: 'portogallo',
    name: 'Portogallo',
    country_code: 'PT',
    flag_emoji: '🇵🇹',
    region: 'europa',
    cities: ['Lisbona', 'Porto', 'Alentejo', 'Algarve'],
    tags: ['Weekend', 'Economico', 'Mare'],
    member_count: 452,
    is_trending: false,
    is_emerging: false,
    groups: [
      { id: 'g4', name: 'Portogallo — tutto l\'anno', whatsapp_url: 'https://chat.whatsapp.com/esempio3', member_count: 310, max_members: 1024, is_active: true },
      { id: 'g5', name: 'Lisbona — consigli pratici', whatsapp_url: 'https://chat.whatsapp.com/esempio4', member_count: 142, max_members: 1024, is_active: true },
    ],
  },
  {
    id: '3',
    slug: 'vietnam',
    name: 'Vietnam',
    country_code: 'VN',
    flag_emoji: '🇻🇳',
    region: 'asia',
    cities: ['Hanoi', 'Hoi An', 'Ho Chi Minh'],
    tags: ['Avventura', 'Budget', 'Street food'],
    member_count: 814,
    is_trending: true,
    is_emerging: false,
    groups: [
      { id: 'g6', name: 'Vietnam — nord e sud', whatsapp_url: 'https://chat.whatsapp.com/esempio5', member_count: 580, max_members: 1024, is_active: true },
      { id: 'g7', name: 'Vietnam inverno 2025/26', whatsapp_url: 'https://chat.whatsapp.com/esempio6', member_count: 234, max_members: 1024, is_active: true },
    ],
  },
  {
    id: '4',
    slug: 'messico',
    name: 'Messico',
    country_code: 'MX',
    flag_emoji: '🇲🇽',
    region: 'america',
    cities: ['CDMX', 'Oaxaca', 'Yucatán', 'Baja'],
    tags: ['Cultura', 'Gastronomia', 'Natura'],
    member_count: 474,
    is_trending: false,
    is_emerging: false,
    groups: [
      { id: 'g8', name: 'Messico — viaggiatori italiani', whatsapp_url: 'https://chat.whatsapp.com/esempio7', member_count: 376, max_members: 1024, is_active: true },
      { id: 'g9', name: 'Oaxaca & dintorni', whatsapp_url: 'https://chat.whatsapp.com/esempio8', member_count: 98, max_members: 1024, is_active: true },
    ],
  },
  {
    id: '5',
    slug: 'marocco',
    name: 'Marocco',
    country_code: 'MA',
    flag_emoji: '🇲🇦',
    region: 'africa',
    cities: ['Marrakech', 'Fès', 'Sahara', 'Essaouira'],
    tags: ['Deserto', 'Souk', 'Vicino'],
    member_count: 289,
    is_trending: false,
    is_emerging: false,
    groups: [
      { id: 'g10', name: 'Marocco — consigli e sicurezza', whatsapp_url: 'https://chat.whatsapp.com/esempio9', member_count: 289, max_members: 1024, is_active: true },
    ],
  },
  {
    id: '6',
    slug: 'georgia',
    name: 'Georgia',
    country_code: 'GE',
    flag_emoji: '🇬🇪',
    region: 'europa',
    cities: ['Tbilisi', 'Kazbegi', 'Kutaisi'],
    tags: ['Off-track', 'Vino', 'Montagna'],
    member_count: 167,
    is_trending: false,
    is_emerging: true,
    groups: [
      { id: 'g11', name: 'Georgia — italiani in Caucaso', whatsapp_url: 'https://chat.whatsapp.com/esempio10', member_count: 167, max_members: 1024, is_active: true },
    ],
  },
]

export const tips: Tip[] = [
  {
    id: 't1',
    destination_slug: 'giappone',
    destination_name: 'Tokyo',
    flag_emoji: '🇯🇵',
    author_initials: 'MR',
    author_name: 'Marco R.',
    weeks_ago: 2,
    content: 'La Suica card conviene sempre, anche per i convenience store. Caricatela direttamente dall\'app Wallet su iPhone senza bisogno di andare in stazione.',
    tags: ['Trasporti', 'Pratico'],
    likes: 47,
    category: 'trasporti',
  },
  {
    id: 't2',
    destination_slug: 'portogallo',
    destination_name: 'Porto',
    flag_emoji: '🇵🇹',
    author_initials: 'SF',
    author_name: 'Sara F.',
    weeks_ago: 4,
    content: 'Evitate i francesinha nei ristoranti turistici di Ribeira. Andate da Santiago (Rua de Passos Manuel 226), costa 9€ ed è autentica al 100%.',
    tags: ['Ristoranti', 'Local'],
    likes: 31,
    category: 'ristoranti',
  },
  {
    id: 't3',
    destination_slug: 'vietnam',
    destination_name: 'Hoi An',
    flag_emoji: '🇻🇳',
    author_initials: 'LB',
    author_name: 'Luca B.',
    weeks_ago: 3,
    content: 'Per l\'affitto moto a Hoi An: chiedete sempre l\'assicurazione e scattate foto al mezzo prima di partire. I depositi inventati sono lo schema classico per i turisti.',
    tags: ['Sicurezza', 'Moto'],
    likes: 89,
    category: 'sicurezza',
  },
  {
    id: 't4',
    destination_slug: 'messico',
    destination_name: 'Oaxaca',
    flag_emoji: '🇲🇽',
    author_initials: 'AG',
    author_name: 'Anna G.',
    weeks_ago: 1,
    content: 'Il mercato di Tlacolula la domenica mattina è 10 volte più autentico di quello di Oaxaca città. Vale assolutamente il bus da 20 pesos.',
    tags: ['Mercati', 'Off-track'],
    likes: 62,
    category: 'cultura',
  },
]
